image: node:9.11.1

pages:
  cache:
    paths:
    - docs/node_modules/
  script:
  - cd docs
  - npm install
  - npm run docs:build
  - mkdir public
  - mv mypublic/* public
  artifacts:
    paths:
    - public
  only:
  - master